config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
	get  '/signup',  to: 'users#new'
	root   'static_pages#home'
  get    '/home',             to: 'static_pages#home'
	get    '/login',            to: 'sessions#new'
	post   '/login',            to: 'sessions#create'
	delete '/logout',           to: 'sessions#destroy'
	resources :users do
    member do
      get :following, :followers
    end
  end
	resource  :family,           only: [:new, :create, :edit, :update, :show]
	resource  :asset_allocation, only: [:new, :create, :edit, :update, :show]
	resources :monthly_expenses, only: [:create, :destroy]
	resources :relationships,    only: [:create, :destroy]
	resources :likes, only: [:create, :destroy]
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :user

	validates :user_id,  presence: true
	validates :spouse,   presence: false,
											 inclusion: { in: [true, false] }
	validates :children, presence: true,
											 numericality: { only_integer: true,
																			 greater_than_or_equal_to: 0,
																			 less_than_or_equal_to: 20 }
	validates :parent,   presence: true,
											 numericality: { only_integer: true,
																			 greater_than_or_equal_to: 0,
																			 less_than_or_equal_to: 4 }
	validates :worker,   presence: true,
											 numericality: { only_integer: true,
																			 greater_than_or_equal_to: 0 }
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  def new
		@family = current_user.build_family if logged_in?
  end

  def edit
		@family = current_user.family
  end

  def show
		@family = current_user.build_family if logged_in?
  end

	def create
		@family = current_user.build_family(family_params)
		if @family.save
			flash[:success] = "世帯構成を登録しました"
			if current_user.asset_allocation.nil?
				redirect_to new_asset_allocation_url 
			else
				redirect_to current_user
			end
		else
			render 'new'
		end
	end

	def update
		@family = current_user.family
    if @family.update(family_params)
      flash[:success] = "世帯構成を更新しました"
      redirect_to current_user 
    else
      render 'edit'
    end
	end

	private
		def family_params
			params.require(:family).permit(:spouse, :children, :parent, :worker)
		end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_family_show.html.erb
<section class="user_info">
	<h1 style="margin-bottom: 20px;"><i class="fas fa-users"></i> 世帯構成</h1>
  <table class="table">
    <tbody>
      <td>配偶者</td>
      <td><%= @family.spouse ? "あり" : "なし" unless @family.nil? %></td>
    </tbody>
    <tbody>
      <td>子供</td>
      <td><%= @family.children unless @family.nil? %>人</td>
    </tbody>
    <tbody>
      <td>親</td>
      <td><%= @family.parent unless @family.nil? %>人</td>
    </tbody>
    <tbody>
      <td>働き手</td>
      <td><%= @family.worker unless @family.nil? %>人</td>
    </tbody>
  </table>
</section>

app/views/families/edit.html.erb
<% provide(:title, "世帯情報の編集") %>
<% provide(:button_text, '世帯情報の更新') %>
<h1>世帯情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 d-flex input-form">
    <%= form_with(model: @family, url: family_path, local: true, method: :patch) do |f| %>
      <%= f.label :spouse, '配偶者の有無' %>
      <%= f.check_box :spouse, class: 'form-control' %>

      <%= f.label :children, '子供の人数' %>
      <%= f.number_field :children, in: 0..10, class: 'form-control', required: true %>

      <%= f.label :parent, '同居している親の人数' %>
      <%= f.number_field :parent, in: 0..6, class: 'form-control', required: true %>

      <%= f.label :worker, '世帯内で働いている人数' %>
      <%= f.number_field :worker, in: 0..8, class: 'form-control', required: true %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/families/new.html.erb
<% provide(:title, "世帯情報の入力") %>
<% provide(:button_text, '世帯情報の登録') %>
<h1>世帯情報の入力</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 d-flex">
		<%= form_with(model: @family, url: family_path, local: true) do |f| %>

			<%= f.label :spouse, '配偶者の有無' %>
  		<%= f.check_box :spouse, class: 'form-control' %>

  		<%= f.label :children, '子供の人数' %>
  		<%= f.number_field :children, value: 0, in: 0..10, class: 'form-control' %>

  		<%= f.label :parent, '同居している親の人数' %>
  		<%= f.number_field :parent, value: 0, in: 0..6 , class: 'form-control' %>

  		<%= f.label :worker, '世帯内で働いている人数' %>
  		<%= f.number_field :worker, value: 0, in: 0..8 , class: 'form-control' %>

			<div class="d-flex">
  			<%= f.submit yield(:button_text), class: "btn btn-primary" %>
				<%= link_to "今はスキップ", new_asset_allocation_path, class: "btn btn-primary" %>
			</div>
		<% end %>
  </div>
</div>

app/views/families/show.html.erb
<% provide(:title, "世帯情報の入力") %>
<% provide(:button_text, '世帯情報の登録') %>
<h1>世帯情報の入力</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 d-flex">
    <%= form_with(model: @family, url: family_path, local: true) do |f| %>
      <%= f.label :spouse, '配偶者の有無' %>
      <%= f.check_box :spouse, class: 'form-control' %>

      <%= f.label :children, '子供の人数' %>
      <%= f.number_field :children, value: 0, in: 0..10, class: 'form-control' %>

      <%= f.label :parent, '同居している親の人数' %>
      <%= f.number_field :parent, value: 0, in: 0..6 , class: 'form-control' %>

      <%= f.label :worker, '世帯内で働いている人数' %>
      <%= f.number_field :worker, value: 0, in: 0..8 , class: 'form-control' %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>