config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
	get  '/signup',  to: 'users#new'
	root   'static_pages#home'
  get    '/home',             to: 'static_pages#home'
	get    '/login',            to: 'sessions#new'
	post   '/login',            to: 'sessions#create'
	delete '/logout',           to: 'sessions#destroy'
	resources :users do
    member do
      get :following, :followers
    end
  end
	resource  :family,           only: [:new, :create, :edit, :update, :show]
	resource  :asset_allocation, only: [:new, :create, :edit, :update, :show]
	resources :monthly_expenses, only: [:create, :destroy]
	resources :relationships,    only: [:create, :destroy]
	resources :likes, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
	has_one  :family,           dependent: :destroy
	has_one  :asset_allocation, dependent: :destroy
	has_many :monthly_expenses, dependent: :destroy
	has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
	has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :follower
	has_many :likes, dependent: :destroy

	scope :search_by_keyword, -> (keyword) {
    where("users.name LIKE :keyword", keyword: "%#{sanitize_sql_like(keyword)}%") if keyword.present?
  }

	validates :name,  presence: true, 
										length: { in: 3..50 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
										length: { maximum: 255 }, 
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }
	before_save :downcase_email

	VALID_USER_NAME_REGEX = /\A[a-z0-9_]+\z/i
	validates :user_name, presence: true, 
												length: { in: 5..15 }, 
												format: { with: VALID_USER_NAME_REGEX }, 
												uniqueness: { case_sensitive: false }
	before_save :downcase_user_name

	has_one_attached :avatar
	validates :avatar, content_type: { in: %w[image/jpeg image/gif image/png],
                                     message: "must be a valid image format" },
                     size:         { less_than: 5.megabytes,
                                     message: "should be less than 5MB" }

	has_secure_password
	validates :password, presence: true,
											 length: { minimum: 6 },
											 allow_nil: true

	def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

	def resize_avatar
		self.avatar.variant(resize_to_limit: [150, 150])
	end

	# ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

	def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    MonthlyExpense.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

	private
		def downcase_email
			self.email.downcase!
		end

		def downcase_user_name
			self.user_name.downcase!
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:edit, :update, :index, :following, :followers]
	before_action :correct_user,   only: [:edit, :update]
	before_action :admin_user,     only: :destroy

	def index
		if params[:q]
      @users = User.search_by_keyword(params[:q])
                        .paginate(page: params[:page], per_page: 10)
    else
			@users = User.paginate(page: params[:page], per_page: 10)
		end
	end

	def show
		@user = User.find(params[:id])
		@monthly_expense = current_user.monthly_expenses.build if logged_in?
		@family = @user.family
		@asset_allocation = @user.asset_allocation
		if not @asset_allocation.nil?
			@asset_allocation_for_graph = {'国内通貨預金' => @asset_allocation.domestic_currency_deposits,
																	 '海外通貨預金' => @asset_allocation.foreign_currency_deposits,
																	 '国内株式'     => @asset_allocation.domestic_stocks,
																	 '海外株式'    => @asset_allocation.foreign_stocks,
																	 '国内債券'    => @asset_allocation.domestic_bonds,
																	 '海外債券'    => @asset_allocation.foreign_bonds,
																	 '不動産'      => @asset_allocation.real_estate,
																	 '金'         => @asset_allocation.gold,
																	 '保険'       => @asset_allocation.insurance,
																	 'その他'     => @asset_allocation.others}
		end
		@monthly_expenses = @user.monthly_expenses.paginate(page: params[:page], per_page: 10)
	end

  def new
		@user = User.new
  end

	def create
		@user = User.new(user_params)
		@user.avatar.attach(params[:user][:avatar])
		if @user.save
			log_in @user
			flash[:success] = "アカウント情報を登録しました"
			redirect_to new_family_url 
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:success] = "プロフィールを更新しました"
      redirect_to @user		
		else
			render 'edit'
		end
	end

	def destroy
    delete_user = User.find(params[:id])
		delete_user.destroy
    flash[:success] = "#{delete_user.name}を消去しました"
    redirect_to users_url
  end

	def following
    @title = "フォローリスト"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page], per_page: 10)
    @family = @user.family
    @asset_allocation = @user.asset_allocation
    if not @asset_allocation.nil?
      @asset_allocation_for_graph = {'国内通貨預金' => @asset_allocation.domestic_currency_deposits,
                                   '海外通貨預金' => @asset_allocation.foreign_currency_deposits,
                                   '国内株式'     => @asset_allocation.domestic_stocks,
                                   '海外株式'    => @asset_allocation.foreign_stocks,
                                   '国内債券'    => @asset_allocation.domestic_bonds,
                                   '海外債券'    => @asset_allocation.foreign_bonds,
                                   '不動産'      => @asset_allocation.real_estate,
                                   '金'         => @asset_allocation.gold,
                                   '保険'       => @asset_allocation.insurance,
                                   'その他'     => @asset_allocation.others}
    end
    render 'show_follow'
  end

  def followers
    @title = "フォロワーリスト"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page], per_page: 10)
		@family = @user.family
    @asset_allocation = @user.asset_allocation
    if not @asset_allocation.nil?
      @asset_allocation_for_graph = {'国内通貨預金' => @asset_allocation.domestic_currency_deposits,
                                   '海外通貨預金' => @asset_allocation.foreign_currency_deposits,
                                   '国内株式'     => @asset_allocation.domestic_stocks,
                                   '海外株式'    => @asset_allocation.foreign_stocks,
                                   '国内債券'    => @asset_allocation.domestic_bonds,
                                   '海外債券'    => @asset_allocation.foreign_bonds,
                                   '不動産'      => @asset_allocation.real_estate,
                                   '金'         => @asset_allocation.gold,
                                   '保険'       => @asset_allocation.insurance,
                                   'その他'     => @asset_allocation.others}
    end
    render 'show_follow'
  end

		private
			def user_params
      	params.require(:user).permit(:avatar, 
																		 :name, 
																		 :email,
																		 :user_name,  
																		 :password,
                	                   :password_confirmation)
    	end

			def admin_user
				redirect_to(root_url) unless current_user.admin?
			end

			def correct_user
    		@user = User.find(params[:id])
    		redirect_to(root_url) unless current_user?(@user)
  		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォロー", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

	<%= f.label :avatar, 'アイコン画像' %>
  <%= f.file_field :avatar, accept: "image/jpeg,image/gif,image/png" %>

  <%= f.label :name, 'ニックネーム' %>
  <%= f.text_field :name, class: 'form-control', required: true %>

  <%= f.label :email, 'メールアドレス' %>
  <%= f.email_field :email, class: 'form-control', required: true %>

  <%= f.label :user_name, 'ユーザー名' %>
  <%= f.text_field :user_name, class: 'form-control', required: true %>

  <%= f.label :password, 'パスワード' %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "パスワード（確認用）" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li class="row">
	<div class="col-md-5">
		<%= image_tag user.resize_avatar, class:"avatar" if user.avatar.attached? %>
		<%= image_tag 'kitten.jpg', class:"avatar" if not user.avatar.attached? %>
  	<%= link_to user.name, user %>
		<% if current_user.admin? && !current_user?(user) %>
    	| <%= link_to "削除", user, method: :delete,
      	                            data: { confirm: "本当に削除しますか?" } %>
  	<% end %>
	</div>
	<div class="col-md-6">
		<h4><i class="fas fa-users"></i> 世帯構成</h4>
		<table class="table">
  		<thead>
    		<tr>
      		<th scope="col">配偶者</th>
      		<th scope="col">子供</th>
      		<th scope="col">親</th>
      		<th scope="col">働き手</th>
    		</tr>
  		</thead>
  		<tbody>
    		<tr>
      		<td><%= user.family.spouse ? "あり" : "なし" unless user.family.nil? %></td>
      		<td><%= user.family.children unless user.family.nil? %>人</td>
      		<td><%= user.family.parent unless user.family.nil? %>人</td>
      		<td><%= user.family.worker unless user.family.nil? %>人</td>
    		</tr>
			</tbody>
		</table>
	</div>
</li>

app/views/users/_user_main.html.erb
<section class="user_info">
  <h1>
    <%= image_tag @user.resize_avatar, class: "avatar" if @user.avatar.attached? %>
    <%= image_tag "kitten.jpg", class: "avatar" if not @user.avatar.attached? %>
    <%= @user.name %>
  </h1>

	<% @user ||= current_user %>
	<div class="stats">
  	<a href="<%= following_user_path(@user) %>">
    	<strong id="following" class="stat">
      	<%= @user.following.count %>
    	</strong>
    	フォロー	
  	</a>
		|
  	<a href="<%= followers_user_path(@user) %>">
    	<strong id="followers" class="stat">
      	<%= @user.followers.count %>
    	</strong>
    	フォロワー
  	</a>
	</div>
</section>

app/views/users/edit.html.erb
<% provide(:title, 'ユーザーの編集') %>
<% provide(:button_text, '変更の保存') %>
<h1>プロフィール編集</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3 input-form">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザ一覧') %>
<h1>ユーザ一覧</h1>
<p class="">
	<%= form_tag(users_path, method: :get) do %>
  	<div class="input-group col-md-3">
    	<%= search_field_tag "q", params[:q], class: "form-control", placeholder: "名前検索" %>
      <span class="input-group-btn">
      	<%= submit_tag "検索", class: "btn btn-default" %>
      </span>
    </div>
  <% end %>
</p>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "サインアップ") %>
<% provide(:button_text, 'アカウントの作成') %>
<h1>サインアップ</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 d-flex">
		<%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
		<%= render 'users/user_main' %>
		<%= render 'users/follow_form' if logged_in? %>
		<%= render 'monthly_expenses/monthly_expense_form' %>
		<%= render 'families/family_show' %>
		<%= render 'asset_allocations/asset_allocation_show' %>
  </aside>

	<div class="col-md-8">
    <h3>月の支出 (登録件数：<%= @user.monthly_expenses.count %>)</h3>
    <% if @user.monthly_expenses.any? %>
      <ol class="monthly_expenses">
        <%= render @monthly_expenses %>
      </ol>
      <%= will_paginate @monthly_expenses %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
		<%= render 'users/user_main' %>
    <%= render 'users/follow_form' if logged_in? %>
    <%= render 'families/family_show' %>
    <%= render 'asset_allocations/asset_allocation_show' %>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>