config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
	get  '/signup',  to: 'users#new'
	root   'static_pages#home'
  get    '/home',             to: 'static_pages#home'
	get    '/login',            to: 'sessions#new'
	post   '/login',            to: 'sessions#create'
	delete '/logout',           to: 'sessions#destroy'
	resources :users do
    member do
      get :following, :followers
    end
  end
	resource  :family,           only: [:new, :create, :edit, :update, :show]
	resource  :asset_allocation, only: [:new, :create, :edit, :update, :show]
	resources :monthly_expenses, only: [:create, :destroy]
	resources :relationships,    only: [:create, :destroy]
	resources :likes, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer container-fluid">
	<p class="footer-text">Portfolio by Keisuke Akari</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <h2 class="header-left col-md-3"><%= link_to "資産形成アプリ", root_path, id: "logo", style: "color: white;" %></h2>
    <nav class="header-right col-md-9">
      <ul class="nav navbar-nav navbar-right">
				<% if logged_in? %>
					<li><%= link_to "フィード", root_path %></li>
					<li><%= link_to "マイページ", current_user %></li>
					<li><%= link_to "ユーザー一覧", users_path %></li>
					<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "アカウント情報の編集", edit_user_path(current_user) %></li>
              <li><%= link_to "世帯情報の登録", family_path if current_user.family.nil? %></li>
              <li><%= link_to "世帯情報の編集", edit_family_path if not current_user.family.nil? %></li>
              <li><%= link_to "資産配分の登録", asset_allocation_path if current_user.asset_allocation.nil? %></li>
              <li><%= link_to "資産配分の編集", edit_asset_allocation_path if not current_user.asset_allocation.nil? %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
				<% else %>
        	<li><%= link_to "ホーム",   root_path %></li>
        	<li><%= link_to "ログイン", login_path %></li>
				<% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= render 'layouts/shim' %>
  </head>

  <body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    	<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
  </body>
</html>